-- Core table for PIN login roles in Supabase
-- The app stores PIN values as bcrypt hashes in the `pin` column.
create table if not exists public.meseros (
  id bigint generated by default as identity primary key,
  nombre text not null,
  rol text not null default 'waiter' check (rol in ('admin', 'waiter', 'kitchen')),
  pin text,
  activo integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists meseros_rol_idx on public.meseros (rol);
create index if not exists meseros_activo_idx on public.meseros (activo);

-- Maintenance audit for security/ops tasks (pin hardening, cleanup workflows)
create table if not exists public.maintenance_audit (
  id bigint generated by default as identity primary key,
  trigger text not null default 'manual' check (trigger in ('auto', 'manual', 'script')),
  started_at timestamptz not null default now(),
  finished_at timestamptz not null default now(),
  retention_days integer not null default 60,
  rotated_count integer not null default 0,
  hardened_existing_pins integer not null default 0,
  purged_tenants_count integer not null default 0,
  details jsonb,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists maintenance_audit_created_idx on public.maintenance_audit (created_at desc);
create index if not exists maintenance_audit_trigger_idx on public.maintenance_audit (trigger);

create table if not exists public.configuracion_restaurante (
  clave text primary key,
  valor text
);

create table if not exists public.licencia_estado (
  id bigint generated by default as identity primary key,
  estado text not null default 'trial' check (estado in ('trial', 'paid')),
  plan text not null default 'trial-7-days',
  started_at timestamptz not null default now(),
  expires_at timestamptz not null,
  trial_days integer not null default 7,
  payment_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists licencia_estado_created_idx on public.licencia_estado (created_at desc);

create table if not exists public.mesas (
  id bigint generated by default as identity primary key,
  numero integer not null unique,
  capacidad integer not null default 4,
  estado text not null default 'disponible' check (estado in ('disponible', 'ocupada', 'reservada', 'libre')),
  fecha_ocupacion timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  categoria_id bigint references public.categorias(id) on delete set null,
  nombre text not null,
  descripcion text,
  precio numeric(12,2) not null,
  costo numeric(12,2) not null default 0,
  disponible integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists productos_categoria_idx on public.productos (categoria_id);
create index if not exists productos_disponible_idx on public.productos (disponible);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  mesa_id bigint references public.mesas(id) on delete set null,
  mesero_id bigint references public.meseros(id) on delete set null,
  estado text not null default 'abierto' check (estado in ('abierto', 'pagado', 'cancelado')),
  fecha_creacion timestamptz not null default now(),
  minutos_servicio integer,
  created_at timestamptz not null default now()
);

create index if not exists pedidos_estado_idx on public.pedidos (estado);
create index if not exists pedidos_mesa_idx on public.pedidos (mesa_id);

create table if not exists public.detalles_pedido (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  producto_id bigint references public.productos(id) on delete set null,
  cantidad integer not null default 1,
  precio_unitario numeric(12,2) not null,
  notas text,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'cocinando', 'servido')),
  created_at timestamptz not null default now()
);

create index if not exists detalles_pedido_pedido_idx on public.detalles_pedido (pedido_id);

create table if not exists public.facturas (
  id bigint generated by default as identity primary key,
  pedido_id bigint unique references public.pedidos(id) on delete set null,
  numero_dian text,
  total numeric(12,2) not null,
  metodo_pago text,
  xml_dian text,
  estado_dian text not null default 'no_enviado',
  descuento numeric(12,2) default 0,
  descuento_tipo text default 'porcentaje',
  nota_descuento text,
  cufe text,
  fecha_emision timestamptz not null default now()
);

create index if not exists facturas_fecha_idx on public.facturas (fecha_emision desc);

create table if not exists public.caja (
  id bigint generated by default as identity primary key,
  fecha_apertura timestamptz not null default now(),
  monto_apertura numeric(12,2) not null,
  mesero_id_apertura bigint references public.meseros(id) on delete set null,
  fecha_cierre timestamptz,
  monto_cierre numeric(12,2),
  ventas_esperadas numeric(12,2) default 0,
  estado text not null default 'abierta' check (estado in ('abierta', 'cerrada')),
  created_at timestamptz not null default now()
);

create table if not exists public.combos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  precio_especial numeric(12,2),
  activo integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.combo_items (
  id bigint generated by default as identity primary key,
  combo_id bigint not null references public.combos(id) on delete cascade,
  producto_id bigint not null references public.productos(id) on delete cascade,
  cantidad integer not null default 1,
  created_at timestamptz not null default now()
);

insert into public.mesas (numero, capacidad)
select serie.numero, serie.capacidad
from (
  values
    (1, 2), (2, 4), (3, 2), (4, 4), (5, 2),
    (6, 4), (7, 2), (8, 4), (9, 2), (10, 4)
) as serie(numero, capacidad)
where not exists (select 1 from public.mesas);

insert into public.categorias (nombre)
select nombre
from (values ('Bebidas'), ('Platos Fuertes')) as serie(nombre)
where not exists (select 1 from public.categorias);

insert into public.productos (categoria_id, nombre, precio, costo, descripcion, disponible)
select c.id, p.nombre, p.precio, p.costo, p.descripcion, 1
from (
  values
    ('Bebidas', 'Coca Cola', 3500, 1500, null),
    ('Bebidas', 'Limonada', 4000, 800, null),
    ('Platos Fuertes', 'Bandeja Paisa', 25000, 12000, null),
    ('Platos Fuertes', 'Ajiaco', 22000, 10000, null)
) as p(categoria, nombre, precio, costo, descripcion)
join public.categorias c on c.nombre = p.categoria
where not exists (select 1 from public.productos);

-- Optional seeds for development or initial setup.
-- On first secure rotation, weak plain seeds are replaced with strong values and hashed automatically.
insert into public.meseros (nombre, rol, pin, activo)
select 'Acceso Administrador', 'admin', '1234', 1
where not exists (select 1 from public.meseros where rol = 'admin');

insert into public.meseros (nombre, rol, pin, activo)
select 'Terminal Cocina', 'kitchen', '5678', 1
where not exists (select 1 from public.meseros where rol = 'kitchen');

insert into public.meseros (nombre, rol, pin, activo)
select 'Terminal Mesero', 'waiter', '0000', 1
where not exists (select 1 from public.meseros where rol = 'waiter');
